// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt06CSMEJhnOp0VQblmQuGELAjB5GAhyM',
    appId: '1:968655440990:web:be4b1c94948725c54cf8cf',
    messagingSenderId: '968655440990',
    projectId: 'trackme-2bb32',
    authDomain: 'trackme-2bb32.firebaseapp.com',
    storageBucket: 'trackme-2bb32.appspot.com',
    measurementId: 'G-TWVJP41EVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkMjCX23AS_2W6MbhzNW_hpeDG7-cvviA',
    appId: '1:968655440990:android:f12d5caca42dbef14cf8cf',
    messagingSenderId: '968655440990',
    projectId: 'trackme-2bb32',
    storageBucket: 'trackme-2bb32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTjM83kxnFFsyrxXeyfSXHLGFTj_TRdSY',
    appId: '1:968655440990:ios:42524f6d2f251ae74cf8cf',
    messagingSenderId: '968655440990',
    projectId: 'trackme-2bb32',
    storageBucket: 'trackme-2bb32.appspot.com',
    iosBundleId: 'com.example.trackme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTjM83kxnFFsyrxXeyfSXHLGFTj_TRdSY',
    appId: '1:968655440990:ios:42524f6d2f251ae74cf8cf',
    messagingSenderId: '968655440990',
    projectId: 'trackme-2bb32',
    storageBucket: 'trackme-2bb32.appspot.com',
    iosBundleId: 'com.example.trackme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt06CSMEJhnOp0VQblmQuGELAjB5GAhyM',
    appId: '1:968655440990:web:f354149aa76f96274cf8cf',
    messagingSenderId: '968655440990',
    projectId: 'trackme-2bb32',
    authDomain: 'trackme-2bb32.firebaseapp.com',
    storageBucket: 'trackme-2bb32.appspot.com',
    measurementId: 'G-652GR91SRC',
  );
}
